#!/usr/bin/python3
# a program that reads the month and displays its number of days


def months():
    months = {"January": 31, "February": 28, "March": 31, "April": 30,
              "May": 31, "June": 30, "July": 31, "August": 31, "September": 30,
              "October": 31, "November": 30, "December": 31}
    selection = str(input("Enter a month: "))

    for month, days in months.items():
        if selection == month and month == "February":
            print(f"The month of {month} has {days} or 29 days")
        elif selection == month:
            print(f"The month of {month} has {days} days")


for i in range(5):
    months()
